In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [4]:
data=pd.read_csv('../Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [6]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [8]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2025-10-16 00:08:17.432900: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-16 00:08:17.434317: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-16 00:08:17.442650: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-16 00:08:17.465151: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-16 00:08:17.505212: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-16 00:08:17.516232: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-16 00:08:17.543642: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-16 00:08:19.587811: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [15]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/home/suhas/.conda/envs/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [18]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 100381.7188 - mae: 100381.7188 - val_loss: 98527.3828 - val_mae: 98527.3828
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 99655.0156 - mae: 99655.0156 - val_loss: 97045.0547 - val_mae: 97045.0547
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97094.6250 - mae: 97094.6250 - val_loss: 93270.5547 - val_mae: 93270.5547
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 92041.3359 - mae: 92041.3359 - val_loss: 86956.8906 - val_mae: 86956.8906
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84615.6484 - mae: 84615.6484 - val_loss: 78693.3281 - val_mae: 78693.3281
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 75824.9688 - mae: 75824.9688 - val_loss: 70122.2188 - val_mae: 70122.2188
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 67168.6328 - mae: 67168.6328 - val_loss: 62478.8750 - val_mae: 62478.8750
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 60034.7305 - mae: 60034.7305 - val_loss: 56805.1016 - val_mae: 56805.1016
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 55234.7305 - mae: 55234.7305 - val_loss: 53473.4688 - val_mae: 53473.4688
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 52510.7070 - mae: 52510.7070 - val_loss: 51902.7852 - val_mae: 51902.7852
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51220.1094 - mae: 51220.1094 - val_loss: 51334.7930 - val_mae: 51334.7930
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50701.1016 - mae: 50701.1016 - val_loss: 51086.9258 - val_mae: 51086.9258
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50453.6445 - mae: 50453.6445 - val_loss: 50965.8438 - val_mae: 50965.8438
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50329.9883 - mae: 50329.9883 - val_loss: 50887.6758 - val_mae: 50887.6758
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50248.4141 - mae: 50248.4141 - val_loss: 50835.7383 - val_mae: 50835.7383
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50184.8164 - mae: 50184.8164 - val_loss: 50788.2617 - val_mae: 50788.2617
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50131.6367 - mae: 50131.6367 - val_loss: 50745.4414 - val_mae: 50745.4414
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50083.4297 - mae: 50083.4297 - val_loss: 50694.4219 - val_mae: 50694.4219
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50041.8438 - mae: 50041.8438 - val_loss: 50653.5469 - val_mae: 50653.5469
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50006.5352 - mae: 50006.5352 - val_loss: 50624.0195 - val_mae: 50624.0195
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49970.6055 - mae: 49970.6055 - val_loss: 50591.8711 - val_mae: 50591.8711
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49938.3125 - mae: 49938.3125 - val_loss: 50569.5195 - val_mae: 50569.5195
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49908.3242 - mae: 49908.3242 - val_loss: 50537.2266 - val_mae: 50537.2266
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49882.6953 - mae: 49882.6953 - val_loss: 50521.7070 - val_mae: 50521.7070
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49857.4102 - mae: 49857.4102 - val_loss: 50501.5742 - val_mae: 50501.5742
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49830.2656 - mae: 49830.2656 - val_loss: 50488.1406 - val_mae: 50488.1406
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49809.0352 - mae: 49809.0352 - val_loss: 50478.9141 - val_mae: 50478.9141
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49788.4727 - mae: 49788.4727 - val_loss: 50457.5508 - val_mae: 50457.5508
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49769.3906 - mae: 49769.3906 - val_loss: 50447.4492 - val_mae: 50447.4492
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49750.7148 - mae: 49750.7148 - val_loss: 50428.1602 - val_mae: 50428.1602
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49737.1758 - mae: 49737.1758 - val_loss: 50417.9688 - val_mae: 50417.9688
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49721.2031 - mae: 49721.2031 - val_loss: 50403.4492 - val_mae: 50403.4492
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49703.8203 - mae: 49703.8203 - val_loss: 50394.2773 - val_mae: 50394.2773
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49688.6016 - mae: 49688.6016 - val_loss: 50381.9609 - val_mae: 50381.9609
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49677.8086 - mae: 49677.8086 - val_loss: 50369.7422 - val_mae: 50369.7422
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49661.3789 - mae: 49661.3789 - val_loss: 50371.0273 - val_mae: 50371.0273
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49651.2031 - mae: 49651.2031 - val_loss: 50359.0156 - val_mae: 50359.0156
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49636.6523 - mae: 49636.6523 - val_loss: 50353.5664 - val_mae: 50353.5664
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49623.3984 - mae: 49623.3984 - val_loss: 50346.0273 - val_mae: 50346.0273
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49616.2695 - mae: 49616.2695 - val_loss: 50340.5547 - val_mae: 50340.5547
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49604.9922 - mae: 49604.9922 - val_loss: 50334.8242 - val_mae: 50334.8242
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49591.9375 - mae: 49591.9375 - val_loss: 50330.1094 - val_mae: 50330.1094
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49584.4688 - mae: 49584.4688 - val_loss: 50333.6562 - val_mae: 50333.6562
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49575.9648 - mae: 49575.9648 - val_loss: 50318.4570 - val_mae: 50318.4570
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49565.0430 - mae: 49565.0430 - val_loss: 50323.5078 - val_mae: 50323.5078
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49555.2188 - mae: 49555.2188 - val_loss: 50321.2266 - val_mae: 50321.2266
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49549.1680 - mae: 49549.1680 - val_loss: 50317.9648 - val_mae: 50317.9648
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49538.6562 - mae: 49538.6562 - val_loss: 50311.1523 - val_mae: 50311.1523
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49533.0391 - mae: 49533.0391 - val_loss: 50318.0586 - val_mae: 50318.0586
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49527.3086 - mae: 49527.3086 - val_loss: 50309.9805 - val_mae: 50309.9805
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49518.1562 - mae: 49518.1562 - val_loss: 50314.3945 - val_mae: 50314.3945
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49511.2266 - mae: 49511.2266 - val_loss: 50309.3164 - val_mae: 50309.3164
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49503.2969 - mae: 49503.2969 - val_loss: 50319.3906 - val_mae: 50319.3906
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49496.7891 - mae: 49496.7891 - val_loss: 50304.6797 - val_mae: 50304.6797
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49492.9336 - mae: 49492.9336 - val_loss: 50315.0977 - val_mae: 50315.0977
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49485.9844 - mae: 49485.9844 - val_loss: 50303.0938 - val_mae: 50303.0938
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49481.2852 - mae: 49481.2852 - val_loss: 50305.0547 - val_mae: 50305.0547
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49479.0469 - mae: 49479.0469 - val_loss: 50302.3906 - val_mae: 50302.3906
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49468.4336 - mae: 49468.4336 - val_loss: 50305.6875 - val_mae: 50305.6875
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49462.5859 - mae: 49462.5859 - val_loss: 50296.2969 - val_mae: 50296.2969
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49458.4609 - mae: 49458.4609 - val_loss: 50298.6602 - val_mae: 50298.6602
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49452.4297 - mae: 49452.4297 - val_loss: 50302.3398 - val_mae: 50302.3398
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49450.2227 - mae: 49450.2227 - val_loss: 50300.6875 - val_mae: 50300.6875
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49441.3906 - mae: 49441.3906 - val_loss: 50300.8984 - val_mae: 50300.8984
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49440.6953 - mae: 49440.6953 - val_loss: 50290.8281 - val_mae: 50290.8281
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49436.5078 - mae: 49436.5078 - val_loss: 50304.6719 - val_mae: 50304.6719
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49429.3906 - mae: 49429.3906 - val_loss: 50307.4102 - val_mae: 50307.4102
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49419.8008 - mae: 49419.8008 - val_loss: 50298.7383 - val_mae: 50298.7383
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49420.2812 - mae: 49420.2812 - val_loss: 50305.6055 - val_mae: 50305.6055
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49415.0039 - mae: 49415.0039 - val_loss: 50309.3750 - val_mae: 50309.3750
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49410.2812 - mae: 49410.2812 - val_loss: 50307.9258 - val_mae: 50307.9258
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49406.1602 - mae: 49406.1602 - val_loss: 50300.5781 - val_mae: 50300.5781
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49401.6602 - mae: 49401.6602 - val_loss: 50296.0703 - val_mae: 50296.0703
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49398.0625 - mae: 49398.0625 - val_loss: 50308.1914 - val_mae: 50308.1914
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49394.6250 - mae: 49394.6250 - val_loss: 50312.5234 - val_mae: 50312.5234

In [19]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [20]:
%load_ext tensorboard

In [21]:
%tensorboard --logdir regressionlogs/fit